bin_dir="/usr/local/bin"
man_dir="/usr/local/share/man"
config_path="/usr/local/etc/mtlf.conf:/etc/mtlf.conf:~/.mtlf/mtlf.conf:./mtlf.conf"
data_path="/usr/local/share/data.json:/usr/share/data.json:~/.mtlf/data.json"
python_path="/usr/local/lib/python3.15"
